cmake_minimum_required(VERSION 3.8)
project(hsl_perception)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
foreach(dependency rclcpp nav_msgs sensor_msgs std_msgs)
  find_package(${dependency} REQUIRED)
endforeach()
add_executable(opponent_detector src/opponent_detector.cpp)
target_include_directories(opponent_detector PRIVATE include)
ament_target_dependencies(opponent_detector rclcpp nav_msgs sensor_msgs std_msgs)
target_compile_options(opponent_detector PRIVATE -Wall -Wextra -Wpedantic)
install(TARGETS opponent_detector DESTINATION lib/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_gtest REQUIRED)
  ament_add_gtest(test_detector test/test_detector.cpp)
  target_include_directories(test_detector PRIVATE include)
endif()
ament_package()
