<?xml version="1.0"?>
<package format="3">
  <name>hsl_real</name><version>0.1.0</version>
  <description>Real Kobuki drivers and autonomous stack integration.</description>
  <maintainer email="dev@just-robotics.ru">Just Robotics</maintainer><license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend><exec_depend>tf2_ros</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>nav_msgs</exec_depend><exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend><exec_depend>hsl_sim_adapter</exec_depend>
  <exec_depend>hsl_decision</exec_depend><exec_depend>hsl_planning</exec_depend>
  <exec_depend>hsl_lidar_filter</exec_depend><exec_depend>hsl_nav2_control</exec_depend>
  <exec_depend>hsl_debug_control</exec_depend><exec_depend>python3-yaml</exec_depend>
  <exec_depend>nav2_amcl</exec_depend><exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend><exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>geometry_msgs</exec_depend><exec_depend>std_msgs</exec_depend>
  <export><build_type>ament_python</build_type></export>
  <exec_depend>jr_perception</exec_depend><exec_depend>jr_launch</exec_depend>
  <exec_depend>linefit_ground_segmentation_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
</package>
