cmake_minimum_required(VERSION 3.8)
project(hsl_lidar_filter)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(std_msgs REQUIRED)
add_executable(real_lidar_filter src/lidar_filter.cpp)
target_compile_features(real_lidar_filter PUBLIC cxx_std_17)
target_compile_options(real_lidar_filter PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(real_lidar_filter rclcpp sensor_msgs std_msgs)
install(TARGETS real_lidar_filter DESTINATION lib/${PROJECT_NAME})
ament_package()
