<?xml version="1.0"?>
<package format="3">
  <name>jr_rviz_plugins</name>
  <version>0.1.0</version>
  <description>RViz panel showing the duel status.</description>

  <maintainer email="dev@just-robotics.ru">Just Robotics</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rviz_common</depend>
  <depend>pluginlib</depend>
  <depend>jr_msgs</depend>
  <depend>qtbase5-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rviz plugin="${prefix}/plugins_description.xml"/>
  </export>
</package>
